// Generated by scripts/shared-generate-brand.sh from brand.json.
// Do not edit by hand. Re-run the script after changing brand.json.
@file:Suppress("unused")

package dev.peterdsp.poravia.core

import kotlin.native.ObjCName

/**
 * Product identity, generated from the repository-level brand.json.
 *
 * The invented product name is suggested by the Greek word for a passage,
 * ford or strait. It is not itself a Greek word and carries no verified
 * translation.
 */
@ObjCName("PoraviaBrand")
object Brand {
    const val NAME: String = "Poravia"
    const val SLUG: String = "poravia"
    const val DOMAIN: String = "poravia.peterdsp.dev"
    const val URL: String = "https://poravia.peterdsp.dev"
    const val SUPPORT_EMAIL: String = "info@peterdsp.dev"
    const val BUNDLE_ID: String = "dev.peterdsp.poravia"
    const val ANDROID_APPLICATION_ID: String = "dev.peterdsp.poravia"
    const val ANDROID_PACKAGE: String = "dev.peterdsp.poravia"
    const val URL_SCHEME: String = "poravia"
    const val ENV_PREFIX: String = "PORAVIA"
    const val CONTRACT_VERSION: String = "1.0.0"
    const val VERSION: String = "1.0.0"
    const val REPOSITORY: String = "https://github.com/peterdsp/Poravia"
    const val DEFAULT_LANGUAGE: String = "el"

    val LANGUAGES: List<String> = listOf("el", "en", "sq")
    val TAGLINE: Map<String, String> = mapOf("el" to "Ταξίδεψε με βεβαιότητα.", "en" to "Travel with certainty.", "sq" to "Udhëto me siguri.")

    /** Base URL for published static data packs. */
    const val STATIC_PACKS_BASE_URL: String = URL + "/data"

    /** https deep-link prefix validated by every client. */
    const val DEEP_LINK_HTTPS_PREFIX: String = URL

    /** Custom scheme deep-link prefix validated by every client. */
    const val DEEP_LINK_SCHEME_PREFIX: String = URL_SCHEME + "://"

    fun tagline(languageTag: String): String =
        TAGLINE[languageTag] ?: TAGLINE[DEFAULT_LANGUAGE] ?: NAME
}
