// Generated by scripts/generate-design-tokens.sh from design/tokens/odivrelo.tokens.json.
// Do not edit by hand. Re-run the script after changing the design tokens.

package dev.peterdsp.odivrelo.theme

import androidx.compose.ui.graphics.Color

/** The Odivrelo semantic palette, one object per appearance. */
object OdivreloPalette {
    /** Brand colours, identical in both appearances. */
    object Brand {
        val deepTealBlue = Color(0xFF0B4A6B)
        val warmOrange = Color(0xFFFF9F2E)
        val lightBackground = Color(0xFFE6F1F7)
        val navy = Color(0xFF082F45)
        val night = Color(0xFF06131C)
    }

    object Light {
        val background = Color(0xFFF4F8FB)
        val surface = Color(0xFFFFFFFF)
        val surfaceMuted = Color(0xFFE6F1F7)
        val neutralSurface = Color(0xFFE3ECF1)
        val surfaceContainerHigh = Color(0xFFD2E7F2)
        val surfaceContainerHighest = Color(0xFFD2E7F2)
        val textPrimary = Color(0xFF082F45)
        val textSecondary = Color(0xFF45596A)
        val border = Color(0xFFC9D8E1)
        val borderStrong = Color(0xFF687F90)
        val outline = Color(0xFF45596A)
        val primary = Color(0xFF0B4A6B)
        val primaryPressed = Color(0xFF083A55)
        val primarySoft = Color(0xFFD2E7F2)
        val primaryInk = Color(0xFF083A55)
        val onPrimary = Color(0xFFFFFFFF)
        val accent = Color(0xFFFF9F2E)
        val accentInk = Color(0xFF4A2800)
        val focus = Color(0xFFFF9F2E)
        val focusRing = Color(0xFF083A55)
        val warningSurface = Color(0xFFFFE9CC)
        val warningText = Color(0xFF4A2800)
        val errorSurface = Color(0xFFFCE8E5)
        val errorText = Color(0xFF8F2F25)
        val successSurface = Color(0xFFE3F3E9)
        val successText = Color(0xFF185C38)
        val infoSurface = Color(0xFFE5F0FA)
        val infoText = Color(0xFF174F83)
        val markRing = Color(0xFF0B4A6B)
        val markRoad = Color(0xFF082F45)
    }

    object Dark {
        val background = Color(0xFF06131C)
        val surface = Color(0xFF0C1F2B)
        val surfaceMuted = Color(0xFF12293A)
        val neutralSurface = Color(0xFF12293A)
        val surfaceContainerHigh = Color(0xFF183447)
        val surfaceContainerHighest = Color(0xFF1E3E53)
        val textPrimary = Color(0xFFF2F7FA)
        val textSecondary = Color(0xFFB3C6D3)
        val border = Color(0xFF2A4557)
        val borderStrong = Color(0xFF6A8497)
        val outline = Color(0xFF8FA7B8)
        val primary = Color(0xFF7CC4E8)
        val primaryPressed = Color(0xFFA9D8EF)
        val primarySoft = Color(0xFF123A52)
        val primaryInk = Color(0xFFBEE3F5)
        val onPrimary = Color(0xFF04202E)
        val accent = Color(0xFFFF9F2E)
        val accentInk = Color(0xFF4A2800)
        val focus = Color(0xFFFF9F2E)
        val focusRing = Color(0xFFFFD08F)
        val warningSurface = Color(0xFF4A3312)
        val warningText = Color(0xFFFFD9A3)
        val errorSurface = Color(0xFF47231F)
        val errorText = Color(0xFFFFB4AA)
        val successSurface = Color(0xFF173C29)
        val successText = Color(0xFF9DDFB5)
        val infoSurface = Color(0xFF19354F)
        val infoText = Color(0xFFA7D2FF)
        val markRing = Color(0xFFFFFFFF)
        val markRoad = Color(0xFFFFFFFF)
    }
}
