#!/usr/bin/env python3
"""Writes the three strings.xml files from one table so the key sets cannot drift.

Greek is the default language and lives in values/. English and Albanian live in
values-en/ and values-sq/. A unit test in the module re-checks that all three
carry exactly the same keys, so a later hand edit that forgets one fails the build.
"""
import html
import os
import sys

ROOT = sys.argv[1]

# key, el, en, sq
S = [
    # -- Identity ---------------------------------------------------------------
    ("app_name", "Odivrelo", "Odivrelo", "Odivrelo"),
    ("app_tagline", "Ταξίδεψε με βεβαιότητα.", "Travel with certainty.", "Udhëto me siguri."),
    ("app_purpose", "Υπεραστικά λεωφορεία, με σαφή προέλευση δεδομένων.",
     "Long-distance coaches, with the source of every fact shown.",
     "Autobusë ndërqytetas, me burimin e çdo fakti të treguar."),

    # -- Actions ----------------------------------------------------------------
    ("action_retry", "Δοκίμασε ξανά", "Try again", "Provo përsëri"),
    ("action_cancel", "Άκυρο", "Cancel", "Anulo"),
    ("action_close", "Κλείσιμο", "Close", "Mbyll"),
    ("action_back", "Πίσω", "Back", "Kthehu"),
    ("action_search", "Αναζήτηση", "Search", "Kërko"),
    ("action_open", "Άνοιγμα", "Open", "Hap"),
    ("action_save", "Αποθήκευση", "Save", "Ruaj"),
    ("action_remove", "Αφαίρεση", "Remove", "Hiq"),
    ("action_delete", "Διαγραφή", "Delete", "Fshi"),
    ("action_download", "Λήψη", "Download", "Shkarko"),
    ("action_update", "Ενημέρωση", "Update", "Përditëso"),
    ("action_continue", "Συνέχεια", "Continue", "Vazhdo"),
    ("action_change", "Αλλαγή", "Change", "Ndrysho"),
    ("action_swap", "Αντιστροφή αφετηρίας και προορισμού", "Swap origin and destination",
     "Ndërro nisjen dhe destinacionin"),
    ("action_today", "Σήμερα", "Today", "Sot"),
    ("action_previous_day", "Προηγούμενη ημέρα", "Previous day", "Dita e mëparshme"),
    ("action_next_day", "Επόμενη ημέρα", "Next day", "Dita tjetër"),
    ("action_choose_date", "Επιλογή ημερομηνίας", "Choose a date", "Zgjidh një datë"),
    ("action_filters", "Φίλτρα", "Filters", "Filtrat"),
    ("action_clear_filters", "Καθαρισμός φίλτρων", "Clear filters", "Fshi filtrat"),
    ("action_apply", "Εφαρμογή", "Apply", "Zbato"),
    ("action_settings", "Ρυθμίσεις", "Settings", "Cilësimet"),
    ("action_copy", "Αντιγραφή", "Copy", "Kopjo"),
    ("action_show_more", "Περισσότερα", "Show more", "Shfaq më shumë"),
    ("action_show_less", "Λιγότερα", "Show less", "Shfaq më pak"),

    # -- Loading, empty and error states ---------------------------------------
    ("state_loading", "Φόρτωση…", "Loading…", "Po ngarkohet…"),
    ("state_loading_a11y", "Φορτώνει. Περίμενε.", "Loading. Please wait.",
     "Po ngarkohet. Prit."),
    ("state_offline_title", "Χωρίς σύνδεση", "No connection", "Pa lidhje"),
    ("state_offline_body",
     "Δεν υπάρχει σύνδεση τώρα. Ό,τι έχει ληφθεί λειτουργεί κανονικά.",
     "There is no connection right now. Anything already downloaded still works.",
     "Nuk ka lidhje tani. Çdo gjë e shkarkuar funksionon normalisht."),
    ("state_server_error_title", "Η υπηρεσία δεν απάντησε", "The service did not answer",
     "Shërbimi nuk u përgjigj"),
    ("state_server_error_body", "Δοκίμασε ξανά σε λίγο.", "Try again in a moment.",
     "Provo përsëri pas një momenti."),
    ("state_unknown_error_title", "Κάτι πήγε λάθος", "Something went wrong", "Diçka shkoi keq"),
    ("state_no_data_title", "Δεν έχουν εγκατασταθεί δεδομένα",
     "No data is installed yet", "Nuk ka të dhëna të instaluara"),
    ("state_no_data_body",
     "Χωρίς δεδομένα δεν μπορεί να απαντηθεί τίποτα. Κατέβασε τα δεδομένα εκτός σύνδεσης.",
     "Nothing can be answered without data. Download the offline data first.",
     "Pa të dhëna nuk mund të përgjigjet asgjë. Shkarko të dhënat offline."),
    ("state_incomplete_data_title", "Τα δεδομένα είναι ελλιπή", "The data is incomplete",
     "Të dhënat janë të paplota"),
    ("state_incomplete_data_body",
     "Λείπουν αρχεία από την εγκατεστημένη έκδοση. Κατέβασέ τα ξανά.",
     "Files are missing from the installed release. Download them again.",
     "Mungojnë skedarë nga publikimi i instaluar. Shkarkoji përsëri."),
    ("state_unreadable_data_title", "Τα δεδομένα δεν διαβάζονται",
     "The data cannot be read", "Të dhënat nuk lexohen"),
    ("state_release_mismatch_title", "Ασυμφωνία έκδοσης δεδομένων",
     "The data releases do not match", "Publikimet e të dhënave nuk përputhen"),
    ("state_release_mismatch_body",
     "Βρέθηκαν αρχεία από διαφορετικές εκδόσεις δεδομένων και απορρίφθηκαν. Κατέβασε ξανά.",
     "Files from different data releases were found and refused. Download again.",
     "U gjetën skedarë nga publikime të ndryshme dhe u refuzuan. Shkarko përsëri."),
    ("state_storage_full_title", "Δεν υπάρχει χώρος", "There is no space left",
     "Nuk ka më vend"),
    ("state_storage_full_body",
     "Ελευθέρωσε χώρο στη συσκευή και δοκίμασε ξανά.",
     "Free some space on the device and try again.",
     "Liro hapësirë në pajisje dhe provo përsëri."),
    ("state_permission_denied_title", "Χρειάζεται άδεια", "A permission is needed",
     "Nevojitet një leje"),
    ("state_permission_revoked_title", "Η άδεια ανακλήθηκε", "The permission was withdrawn",
     "Leja u tërhoq"),
    ("state_expired_title", "Η ημερομηνία πέρασε", "That date has passed", "Ajo datë ka kaluar"),
    ("state_expired_body", "Διάλεξε μια ημερομηνία από σήμερα και μετά.",
     "Choose a date from today onwards.", "Zgjidh një datë nga sot e tutje."),
    ("state_restricted_title", "Δεν επιτρέπεται η προβολή", "This cannot be shown",
     "Kjo nuk mund të shfaqet"),
    ("state_restricted_body",
     "Η πηγή αυτών των δεδομένων δεν έχει άδεια αναδημοσίευσης.",
     "The source of this data has no permission for reuse.",
     "Burimi i këtyre të dhënave nuk ka leje për ripërdorim."),

    # -- Demonstration data notice ---------------------------------------------
    ("demo_notice_title", "Δεδομένα επίδειξης", "Demonstration data",
     "Të dhëna demonstrimi"),
    ("demo_notice_body",
     "Αυτά τα δεδομένα είναι επινοημένα. Η Αλόρια δεν υπάρχει και κανένα δρομολόγιο εδώ δεν είναι αληθινό.",
     "This data is invented. Aloria does not exist and no departure shown here is real.",
     "Këto të dhëna janë të trilluara. Aloria nuk ekziston dhe asnjë nisje e shfaqur këtu nuk është e vërtetë."),
    ("demo_notice_a11y",
     "Ειδοποίηση: δεδομένα επίδειξης. Η Αλόρια δεν υπάρχει και κανένα δρομολόγιο δεν είναι αληθινό.",
     "Notice: demonstration data. Aloria does not exist and no departure is real.",
     "Vërejtje: të dhëna demonstrimi. Aloria nuk ekziston dhe asnjë nisje nuk është e vërtetë."),

    # -- Tickets ----------------------------------------------------------------
    ("no_tickets_sold",
     "Το Odivrelo δεν πουλά και δεν εκδίδει εισιτήρια.",
     "Odivrelo does not sell or issue tickets.",
     "Odivrelo nuk shet dhe nuk lëshon bileta."),
    ("no_tickets_sold_short", "Δεν πουλάμε εισιτήρια", "We do not sell tickets",
     "Nuk shesim bileta"),

    # -- Data quality labels ----------------------------------------------------
    ("freshness_fresh", "Πρόσφατο", "Fresh", "I freskët"),
    ("freshness_aging", "Παλαιώνει", "Aging", "Po plaket"),
    ("freshness_stale", "Παλιό", "Stale", "I vjetër"),
    ("freshness_checked_hours", "Ελέγχθηκε πριν %1$d ώρες", "Checked %1$d hours ago",
     "Kontrolluar %1$d orë më parë"),
    ("freshness_checked_days", "Ελέγχθηκε πριν %1$d ημέρες", "Checked %1$d days ago",
     "Kontrolluar %1$d ditë më parë"),
    ("freshness_checked_recently", "Ελέγχθηκε μόλις τώρα", "Checked just now",
     "Kontrolluar tani"),
    ("quality_scheduled", "Από πρόγραμμα", "Scheduled", "Sipas planit"),
    ("quality_approximate", "Κατά προσέγγιση", "Approximate", "I përafërt"),
    ("quality_unknown", "Άγνωστη ώρα", "Time unknown", "Ora e panjohur"),
    ("quality_scheduled_help",
     "Η ώρα προέρχεται από δημοσιευμένο πρόγραμμα, όχι από παρατήρηση.",
     "This time comes from a published timetable, not from an observation.",
     "Kjo orë vjen nga një orar i publikuar, jo nga vëzhgimi."),
    ("quality_approximate_help",
     "Ο μεταφορέας δίνει κατά προσέγγιση ώρα για αυτή τη στάση.",
     "The operator gives only an approximate time for this stop.",
     "Operatori jep vetëm një orë të përafërt për këtë ndalesë."),
    ("live_unavailable_title", "Χωρίς ζωντανή παρακολούθηση", "No live tracking",
     "Pa gjurmim të drejtpërdrejtë"),
    ("live_unavailable_body",
     "Αυτή η έκδοση δείχνει μόνο το πρόγραμμα. Δεν υπάρχει ζωντανή θέση οχήματος.",
     "This release shows the timetable only. There is no live vehicle position.",
     "Ky publikim tregon vetëm orarin. Nuk ka pozicion të drejtpërdrejtë të automjetit."),
    ("confidence_reviewed", "Ελεγμένο", "Reviewed", "I rishikuar"),
    ("confidence_candidate", "Υπό έλεγχο", "Not yet reviewed", "Jo i rishikuar"),
    ("confidence_candidate_help",
     "Αυτή η καταχώρηση δεν έχει ελεγχθεί ακόμη από άνθρωπο.",
     "Nobody has reviewed this entry yet.",
     "Askush nuk e ka rishikuar këtë të dhënë."),
    ("geometry_unverified", "Διαδρομή μη επιβεβαιωμένη", "Route not verified",
     "Itinerari i paverifikuar"),
    ("geometry_ordered_stops_only", "Ευθείες μεταξύ στάσεων",
     "Straight lines between stops", "Vija të drejta mes ndalesave"),
    ("geometry_osm_candidate", "Πιθανή διαδρομή από OpenStreetMap",
     "Candidate route from OpenStreetMap", "Itinerar i mundshëm nga OpenStreetMap"),
    ("geometry_reviewed", "Ελεγμένη διαδρομή", "Reviewed route", "Itinerar i rishikuar"),
    ("geometry_none", "Δεν υπάρχει χάραξη διαδρομής", "No route shape is available",
     "Nuk ka formë itinerari"),

    # -- Coverage ---------------------------------------------------------------
    ("coverage_covered", "Καλύπτεται", "Covered", "Mbulohet"),
    ("coverage_partial", "Καλύπτεται εν μέρει", "Partly covered", "Mbulohet pjesërisht"),
    ("coverage_not_covered", "Δεν καλύπτεται", "Not covered", "Nuk mbulohet"),
    ("coverage_demo", "Επίδειξη", "Demonstration", "Demonstrim"),
    ("coverage_not_covered_title", "Τι δεν καλύπτεται", "What is not covered",
     "Çfarë nuk mbulohet"),
    ("coverage_absence_title", "Τι σημαίνει η απουσία δρομολογίου",
     "What the absence of a journey means", "Çfarë do të thotë mungesa e një udhëtimi"),

    # -- Accessibility of a boarding point --------------------------------------
    ("step_free_yes", "Χωρίς σκαλοπάτια", "Step free", "Pa shkallë"),
    ("step_free_no", "Με σκαλοπάτια", "Has steps", "Me shkallë"),
    ("step_free_unknown", "Δεν έχει ελεγχθεί", "Not reviewed", "Nuk është rishikuar"),
    ("step_free_unknown_help",
     "Κανείς δεν έχει ελέγξει αν αυτό το σημείο είναι προσβάσιμο. Αυτό δεν σημαίνει ότι δεν είναι.",
     "Nobody has checked whether this boarding point is step free. That is not the same as it having steps.",
     "Askush nuk ka kontrolluar nëse kjo pikë është pa shkallë. Kjo nuk është e njëjta me të pasur shkallë."),

    # -- First run --------------------------------------------------------------
    ("welcome_title", "Καλώς όρισες στο Odivrelo", "Welcome to Odivrelo",
     "Mirë se vjen në Odivrelo"),
    ("welcome_language_title", "Διάλεξε γλώσσα", "Choose a language", "Zgjidh një gjuhë"),
    ("welcome_no_account",
     "Δεν χρειάζεται λογαριασμός. Δεν ζητάμε τίποτα για εσένα.",
     "No account is needed. We do not ask anything about you.",
     "Nuk nevojitet llogari. Nuk kërkojmë asgjë për ty."),
    ("welcome_no_tickets",
     "Το Odivrelo δεν πουλά εισιτήρια. Σε στέλνει στον μεταφορέα ή στο εκδοτήριο.",
     "Odivrelo does not sell tickets. It sends you to the operator or the ticket office.",
     "Odivrelo nuk shet bileta. Ju dërgon te operatori ose te zyra e biletave."),
    ("welcome_offline",
     "Λειτουργεί χωρίς σύνδεση, με δεδομένα που κατεβάζεις εσύ.",
     "It works without a connection, using data you download yourself.",
     "Funksionon pa lidhje, me të dhëna që shkarkon vetë."),
    ("welcome_start", "Ξεκίνα", "Start", "Fillo"),

    # -- Navigation -------------------------------------------------------------
    ("nav_search", "Αναζήτηση", "Search", "Kërko"),
    ("nav_saved", "Αποθηκευμένα", "Saved", "Të ruajtura"),
    ("nav_offline", "Εκτός σύνδεσης", "Offline", "Offline"),
    ("nav_wallet", "Εισιτήρια", "Tickets", "Bileta"),
    ("nav_settings", "Ρυθμίσεις", "Settings", "Cilësimet"),

    # -- Search -----------------------------------------------------------------
    ("search_title", "Αναζήτηση δρομολογίου", "Find a journey", "Gjej një udhëtim"),
    ("search_origin_label", "Από", "From", "Nga"),
    ("search_destination_label", "Προς", "To", "Për"),
    ("search_endpoint_empty", "Διάλεξε", "Choose", "Zgjidh"),
    ("search_date_label", "Ημέρα ταξιδιού", "Travel day", "Dita e udhëtimit"),
    ("search_date_zone_note", "Οι ώρες είναι σε ώρα Ελλάδας.",
     "All times are Greek time.", "Të gjitha oraret janë në kohën greke."),
    ("search_recent_title", "Πρόσφατες αναζητήσεις", "Recent searches",
     "Kërkimet e kohëve të fundit"),
    ("search_recent_empty", "Δεν υπάρχουν πρόσφατες αναζητήσεις.", "No recent searches yet.",
     "Nuk ka kërkime të kohëve të fundit."),
    ("search_run", "Αναζήτηση δρομολογίων", "Search journeys", "Kërko udhëtime"),
    ("search_needs_both", "Διάλεξε αφετηρία και προορισμό.",
     "Choose an origin and a destination.", "Zgjidh një nisje dhe një destinacion."),
    ("search_same_endpoints", "Η αφετηρία και ο προορισμός είναι ο ίδιος τόπος.",
     "The origin and destination are the same place.",
     "Nisja dhe destinacioni janë i njëjti vend."),

    # -- Place picker -----------------------------------------------------------
    ("place_picker_origin_title", "Από πού ξεκινάς;", "Where are you starting?",
     "Nga ku po nisesh?"),
    ("place_picker_destination_title", "Πού πηγαίνεις;", "Where are you going?",
     "Ku po shkon?"),
    ("place_picker_hint", "Πληκτρολόγησε όνομα σταθμού ή στάσης",
     "Type a terminal or stop name", "Shkruaj emrin e një terminali ose ndalese"),
    ("place_picker_needs_input", "Γράψε τουλάχιστον δύο χαρακτήρες.",
     "Type at least two characters.", "Shkruaj të paktën dy karaktere."),
    ("place_no_match", "Δεν βρέθηκε τόπος με αυτό το όνομα.",
     "No place matches that name.", "Asnjë vend nuk përputhet me atë emër."),
    ("place_terminal", "Σταθμός", "Terminal", "Terminal"),
    ("place_boarding_point", "Σημείο επιβίβασης", "Boarding point", "Pikë hipjeje"),
    ("place_bay_count", "%1$d σημεία επιβίβασης", "%1$d boarding points",
     "%1$d pika hipjeje"),
    ("place_choose_whole_terminal", "Όλος ο σταθμός", "The whole terminal",
     "I gjithë terminali"),
    ("place_terminal_help",
     "Ο σταθμός περιλαμβάνει όλα τα σημεία επιβίβασης. Διάλεξε ένα συγκεκριμένο αν ξέρεις ποιο θέλεις.",
     "The terminal covers every boarding point. Choose one if you already know which you need.",
     "Terminali përfshin çdo pikë hipjeje. Zgjidh një nëse e di se cilën do."),
    ("place_inside_terminal", "Στον σταθμό %1$s", "At %1$s", "Në %1$s"),

    # -- Filters ----------------------------------------------------------------
    ("filters_title", "Φίλτρα αναζήτησης", "Search filters", "Filtrat e kërkimit"),
    ("filter_accessible", "Μόνο σημεία χωρίς σκαλοπάτια",
     "Step-free boarding points only", "Vetëm pika hipjeje pa shkallë"),
    ("filter_accessible_help",
     "Κρατά μόνο δρομολόγια με ελεγμένο σημείο επιβίβασης χωρίς σκαλοπάτια. Τα μη ελεγμένα αποκλείονται.",
     "Keeps only journeys with a reviewed step-free boarding point. Unreviewed ones are excluded.",
     "Mban vetëm udhëtimet me pikë hipjeje të rishikuar pa shkallë. Të parishikuarat përjashtohen."),
    ("filter_depart_after", "Αναχώρηση από", "Departing after", "Nisja pas"),
    ("filter_depart_before", "Αναχώρηση έως", "Departing before", "Nisja para"),
    ("filter_max_duration", "Μέγιστη διάρκεια", "Longest journey", "Kohëzgjatja maksimale"),
    ("filter_include_overnight", "Συμπερίληψη νυχτερινών δρομολογίων",
     "Include journeys that cross midnight", "Përfshi udhëtimet që kalojnë mesnatën"),
    ("filter_sort", "Ταξινόμηση", "Sort by", "Rendit sipas"),
    ("sort_departure", "Ώρα αναχώρησης", "Departure time", "Ora e nisjes"),
    ("sort_duration", "Διάρκεια", "Duration", "Kohëzgjatja"),
    ("sort_arrival", "Ώρα άφιξης", "Arrival time", "Ora e mbërritjes"),
    ("filters_active", "%1$d φίλτρα ενεργά", "%1$d filters active", "%1$d filtra aktive"),
    ("filter_any", "Χωρίς περιορισμό", "No limit", "Pa kufi"),

    # -- Results ----------------------------------------------------------------
    ("results_title", "Δρομολόγια", "Journeys", "Udhëtime"),
    ("results_for", "%1$s προς %2$s", "%1$s to %2$s", "%1$s në %2$s"),
    ("results_count", "%1$d δρομολόγια", "%1$d journeys", "%1$d udhëtime"),
    ("results_count_one", "1 δρομολόγιο", "1 journey", "1 udhëtim"),
    ("results_empty_no_service_title", "Δεν υπάρχει δρομολόγιο αυτή την ημέρα",
     "No journey runs on that day", "Asnjë udhëtim nuk niset atë ditë"),
    ("results_empty_no_service_body",
     "Τα εγκατεστημένα δεδομένα για αυτή την ημέρα δεν δείχνουν δρομολόγιο σε αυτή τη διαδρομή.",
     "The installed data for that day shows no journey on this pair.",
     "Të dhënat e instaluara për atë ditë nuk tregojnë udhëtim në këtë çift."),
    ("results_empty_no_offline_title", "Δεν υπάρχουν δεδομένα για αυτή την ημέρα",
     "No data for that day on this device", "Pa të dhëna për atë ditë në këtë pajisje"),
    ("results_empty_no_offline_body",
     "Αυτό δεν σημαίνει ότι δεν υπάρχει δρομολόγιο. Η εγκατεστημένη έκδοση απλώς δεν περιλαμβάνει αυτή την ημέρα.",
     "This does not mean no journey runs. The installed release simply does not include that day.",
     "Kjo nuk do të thotë se nuk niset asnjë udhëtim. Publikimi i instaluar thjesht nuk e përfshin atë ditë."),
    ("results_empty_filtered_title", "Τα φίλτρα απέκλεισαν όλα τα δρομολόγια",
     "The filters excluded every journey", "Filtrat përjashtuan çdo udhëtim"),
    ("results_empty_filtered_body", "Χαλάρωσε ή καθάρισε τα φίλτρα.",
     "Loosen or clear the filters.", "Zbut ose fshi filtrat."),
    ("results_empty_outside_title", "Έξω από την κάλυψη", "Outside the covered area",
     "Jashtë zonës së mbuluar"),
    ("results_empty_outside_body",
     "Ένας από τους δύο τόπους δεν καλύπτεται από αυτή την έκδοση δεδομένων.",
     "One of the two places is not covered by this data release.",
     "Një nga dy vendet nuk mbulohet nga ky publikim të dhënash."),
    ("results_partial_coverage_title", "Μερική κάλυψη", "Partial coverage",
     "Mbulim i pjesshëm"),
    ("results_partial_coverage_body",
     "Μερικοί μεταφορείς σε αυτή τη διαδρομή δεν καλύπτονται, άρα η λίστα μπορεί να είναι ελλιπής.",
     "Some operators on this pair are not covered, so this list may be incomplete.",
     "Disa operatorë në këtë çift nuk mbulohen, kështu që lista mund të jetë e paplotë."),
    ("results_cached_release", "Από τοπικά δεδομένα, έκδοση %1$s",
     "From data on this device, release %1$s",
     "Nga të dhënat në këtë pajisje, publikimi %1$s"),
    ("results_from_service", "Απάντηση από την υπηρεσία", "Answered by the service",
     "Përgjigje nga shërbimi"),
    ("results_intermediate_none", "Χωρίς ενδιάμεσες στάσεις", "No intermediate stops",
     "Pa ndalesa të ndërmjetme"),
    ("results_intermediate", "%1$d ενδιάμεσες στάσεις", "%1$d intermediate stops",
     "%1$d ndalesa të ndërmjetme"),
    ("results_intermediate_one", "1 ενδιάμεση στάση", "1 intermediate stop",
     "1 ndalesë e ndërmjetme"),
    ("crosses_midnight", "Περνά τα μεσάνυχτα", "Crosses midnight", "Kalon mesnatën"),
    ("crosses_midnight_detail", "Αναχώρηση %1$s, άφιξη την επόμενη ημέρα %2$s",
     "Departs %1$s, arrives the next day at %2$s",
     "Niset %1$s, mbërrin ditën tjetër në %2$s"),
    ("duration_hours_minutes", "%1$dω %2$dλ", "%1$dh %2$dm", "%1$dh %2$dm"),
    ("duration_minutes", "%1$dλ", "%1$dm", "%1$dm"),
    ("duration_a11y_hours_minutes", "%1$d ώρες και %2$d λεπτά", "%1$d hours %2$d minutes",
     "%1$d orë %2$d minuta"),
    ("duration_a11y_minutes", "%1$d λεπτά", "%1$d minutes", "%1$d minuta"),
    ("fare_indicative", "Ενδεικτική τιμή %1$s", "Indicative fare %1$s",
     "Çmim tregues %1$s"),
    ("fare_indicative_help",
     "Ενδεικτική τιμή από δημοσιευμένη πηγή. Δεν είναι προσφορά και μπορεί να έχει αλλάξει.",
     "An indicative fare from a published source. It is not a quotation and may have changed.",
     "Një çmim tregues nga një burim i publikuar. Nuk është ofertë dhe mund të ketë ndryshuar."),
    ("fare_unknown", "Τιμή άγνωστη", "Fare unknown", "Çmimi i panjohur"),
    ("results_select_hint", "Διάλεξε δρομολόγιο για λεπτομέρειες",
     "Choose a journey to see the details", "Zgjidh një udhëtim për detajet"),

    # -- Journey detail ---------------------------------------------------------
    ("journey_title", "Λεπτομέρειες δρομολογίου", "Journey detail", "Detajet e udhëtimit"),
    ("journey_operating_date", "Ημέρα λειτουργίας", "Operating day", "Dita e funksionimit"),
    ("journey_operator", "Μεταφορέας", "Operator", "Operatori"),
    ("journey_boarding_point", "Σημείο επιβίβασης", "Boarding point", "Pika e hipjes"),
    ("journey_boarding_bay", "Θέση %1$s", "Bay %1$s", "Vendi %1$s"),
    ("journey_boarding_reviewed", "Ελεγμένο στις %1$s", "Reviewed on %1$s",
     "Rishikuar në %1$s"),
    ("journey_boarding_not_reviewed", "Το σημείο επιβίβασης δεν έχει ελεγχθεί.",
     "This boarding point has not been reviewed.", "Kjo pikë hipjeje nuk është rishikuar."),
    ("journey_stops_title", "Στάσεις", "Stops", "Ndalesat"),
    ("journey_stops_count", "%1$d στάσεις", "%1$d stops", "%1$d ndalesa"),
    ("pickup_allowed", "Επιβίβαση", "Boarding", "Hipje"),
    ("pickup_not_allowed", "Χωρίς επιβίβαση", "No boarding", "Pa hipje"),
    ("pickup_on_request", "Επιβίβαση με αίτημα", "Boarding on request", "Hipje me kërkesë"),
    ("pickup_coordinate", "Επιβίβαση κατόπιν συνεννόησης",
     "Boarding by arrangement with the operator", "Hipje me marrëveshje me operatorin"),
    ("dropoff_allowed", "Αποβίβαση", "Alighting", "Zbritje"),
    ("dropoff_not_allowed", "Χωρίς αποβίβαση", "No alighting", "Pa zbritje"),
    ("dropoff_on_request", "Αποβίβαση με αίτημα", "Alighting on request",
     "Zbritje me kërkesë"),
    ("dropoff_coordinate", "Αποβίβαση κατόπιν συνεννόησης",
     "Alighting by arrangement with the operator", "Zbritje me marrëveshje me operatorin"),
    ("journey_restrictions_title", "Περιορισμοί", "Restrictions", "Kufizime"),
    ("journey_restrictions_none", "Δεν έχουν καταγραφεί περιορισμοί.",
     "No restrictions are recorded.", "Nuk janë regjistruar kufizime."),
    ("journey_provenance_title", "Προέλευση δεδομένων", "Where this came from",
     "Nga vjen kjo"),
    ("journey_provenance_retrieved", "Ανακτήθηκε %1$s", "Retrieved %1$s",
     "Marrë %1$s"),
    ("journey_view_map", "Χάρτης", "Map", "Harta"),
    ("journey_view_list", "Λίστα", "List", "Listë"),
    ("journey_map_note",
     "Δεν υπάρχουν χάρτες εκτός σύνδεσης. Ο χάρτης ανοίγει στην εφαρμογή χαρτών της συσκευής.",
     "There are no offline maps. The map opens in the device's own maps application.",
     "Nuk ka harta offline. Harta hapet në aplikacionin e hartave të pajisjes."),
    ("journey_open_in_maps", "Άνοιγμα στους χάρτες", "Open in maps", "Hap në harta"),
    ("journey_no_map_app", "Δεν βρέθηκε εφαρμογή χαρτών σε αυτή τη συσκευή.",
     "No maps application was found on this device.",
     "Nuk u gjet aplikacion hartash në këtë pajisje."),
    ("journey_correction", "Αναφορά λάθους", "Report a mistake", "Raporto një gabim"),
    ("journey_save", "Αποθήκευση ταξιδιού", "Save this trip", "Ruaj këtë udhëtim"),
    ("journey_saved", "Αποθηκευμένο", "Saved", "E ruajtur"),
    ("journey_unsave", "Αφαίρεση από τα αποθηκευμένα", "Remove from saved",
     "Hiq nga të ruajtura"),
    ("journey_from_saved_copy",
     "Αυτό είναι το αποθηκευμένο αντίγραφο, από την έκδοση %1$s.",
     "This is the saved copy, from release %1$s.",
     "Ky është kopja e ruajtur, nga publikimi %1$s."),

    # -- Booking handoff --------------------------------------------------------
    ("booking_title", "Εισιτήρια", "Tickets", "Bileta"),
    ("booking_online_action", "Κράτηση στον μεταφορέα", "Book with the operator",
     "Rezervo te operatori"),
    ("booking_office_title", "Μόνο από εκδοτήριο ή τηλέφωνο",
     "Ticket office or telephone only", "Vetëm zyra e biletave ose telefoni"),
    ("booking_phone", "Τηλέφωνο", "Telephone", "Telefoni"),
    ("booking_address", "Διεύθυνση", "Address", "Adresa"),
    ("booking_hours", "Ώρες λειτουργίας", "Opening hours", "Orari"),
    ("booking_call", "Κλήση", "Call", "Telefono"),
    ("booking_directions", "Οδηγίες", "Directions", "Udhëzime"),
    ("booking_onboard", "Εισιτήρια εντός του οχήματος", "Tickets on board",
     "Bileta në bord"),
    ("booking_unavailable_title", "Δεν ξέρουμε πού πωλούνται εισιτήρια",
     "We do not know where tickets are sold", "Nuk e dimë ku shiten biletat"),
    ("booking_unavailable_body",
     "Δεν έχει επιβεβαιωθεί τρόπος αγοράς για αυτό το δρομολόγιο. Ρώτησε τον μεταφορέα.",
     "No way to buy a ticket has been confirmed for this journey. Ask the operator.",
     "Nuk është konfirmuar mënyra e blerjes për këtë udhëtim. Pyet operatorin."),
    ("booking_leaves_app",
     "Ανοίγει ο ιστότοπος του μεταφορέα. Επιστρέφεις εδώ όπως ήσουν.",
     "This opens the operator's own site. You come back here exactly where you were.",
     "Kjo hap faqen e operatorit. Kthehesh pikërisht ku ishe."),
    ("booking_no_browser", "Δεν βρέθηκε πρόγραμμα περιήγησης σε αυτή τη συσκευή.",
     "No browser was found on this device.",
     "Nuk u gjet shfletues në këtë pajisje."),
    ("booking_no_dialer", "Δεν βρέθηκε εφαρμογή κλήσεων σε αυτή τη συσκευή.",
     "No telephone application was found on this device.",
     "Nuk u gjet aplikacion telefoni në këtë pajisje."),

    # -- Operator ---------------------------------------------------------------
    ("operator_title", "Μεταφορέας", "Operator", "Operatori"),
    ("operator_contact_title", "Επικοινωνία", "Contact", "Kontakti"),
    ("operator_coverage_title", "Κάλυψη", "Coverage", "Mbulimi"),
    ("operator_routes_count", "%1$d διαδρομές", "%1$d routes", "%1$d itinerare"),
    ("operator_stops_count", "%1$d στάσεις", "%1$d stops", "%1$d ndalesa"),
    ("operator_sources_title", "Πηγές", "Sources", "Burimet"),
    ("operator_site", "Επίσημος ιστότοπος", "Official site", "Faqja zyrtare"),
    ("operator_no_site", "Δεν έχει καταγραφεί επίσημος ιστότοπος.",
     "No official site is recorded.", "Nuk është regjistruar faqe zyrtare."),
    ("operator_verified_at", "Επαληθεύτηκε %1$s", "Verified %1$s", "Verifikuar %1$s"),
    ("operator_email", "Ηλεκτρονικό ταχυδρομείο", "Email", "Email"),

    # -- Stop -------------------------------------------------------------------
    ("stop_title", "Στάση", "Stop", "Ndalesa"),
    ("stop_departures_title", "Αναχωρήσεις", "Departures", "Nisjet"),
    ("stop_no_departures", "Δεν υπάρχουν αναχωρήσεις αυτή την ημέρα.",
     "No departures on that day.", "Pa nisje atë ditë."),
    ("stop_boarding_points_title", "Σημεία επιβίβασης", "Boarding points",
     "Pikat e hipjes"),
    ("stop_part_of", "Μέρος του %1$s", "Part of %1$s", "Pjesë e %1$s"),
    ("stop_coordinates", "Συντεταγμένες %1$s, %2$s", "Coordinates %1$s, %2$s",
     "Koordinatat %1$s, %2$s"),

    # -- Favourites and saved trips --------------------------------------------
    ("favorites_title", "Αγαπημένα", "Favourites", "Të preferuara"),
    ("favorites_empty_title", "Δεν έχεις αγαπημένα", "No favourites yet",
     "Pa të preferuara"),
    ("favorites_empty_body",
     "Πρόσθεσε σταθμούς που χρησιμοποιείς συχνά για να τους βρίσκεις αμέσως.",
     "Add terminals you use often so they are one tap away.",
     "Shto terminalet që përdor shpesh për t'i gjetur menjëherë."),
    ("favorite_add", "Προσθήκη στα αγαπημένα", "Add to favourites",
     "Shto te të preferuara"),
    ("favorite_remove", "Αφαίρεση από τα αγαπημένα", "Remove from favourites",
     "Hiq nga të preferuara"),
    ("saved_trips_title", "Αποθηκευμένα ταξίδια", "Saved trips", "Udhëtime të ruajtura"),
    ("saved_trips_empty_title", "Δεν έχεις αποθηκευμένα ταξίδια", "No saved trips yet",
     "Pa udhëtime të ruajtura"),
    ("saved_trips_empty_body",
     "Αποθήκευσε ένα δρομολόγιο και θα το διαβάζεις χωρίς σύνδεση, μαζί με το σημείο επιβίβασης.",
     "Save a journey and you can read it with no connection, boarding point included.",
     "Ruaj një udhëtim dhe mund ta lexosh pa lidhje, bashkë me pikën e hipjes."),
    ("saved_trip_cached", "Αποθηκεύτηκε %1$s από την έκδοση %2$s",
     "Saved %1$s from release %2$s", "Ruajtur %1$s nga publikimi %2$s"),
    ("saved_trip_age_note",
     "Αυτό είναι αντίγραφο. Μπορεί να έχει αλλάξει από τότε.",
     "This is a copy. It may have changed since.",
     "Kjo është një kopje. Mund të ketë ndryshuar ndërkohë."),
    ("trip_ready_title", "Έτοιμο ταξίδι", "Trip Ready", "Udhëtim gati"),
    ("trip_ready_body",
     "Ό,τι χρειάζεσαι στη στάση, χωρίς σύνδεση.",
     "Everything you need at the bay, with no connection.",
     "Çdo gjë që të duhet në ndalesë, pa lidhje."),
    ("trip_ready_offline", "Λειτουργεί χωρίς σύνδεση", "Works with no connection",
     "Funksionon pa lidhje"),

    # -- Offline packs ----------------------------------------------------------
    ("offline_title", "Δεδομένα εκτός σύνδεσης", "Offline data", "Të dhëna offline"),
    ("offline_release", "Έκδοση δεδομένων %1$s", "Data release %1$s",
     "Publikimi i të dhënave %1$s"),
    ("offline_published", "Δημοσιεύτηκε %1$s", "Published %1$s", "Publikuar %1$s"),
    ("offline_total_size", "Εγκατεστημένα %1$s", "%1$s installed", "%1$s të instaluara"),
    ("offline_maps_title", "Τι υπάρχει και τι δεν υπάρχει εκτός σύνδεσης",
     "What is and is not available offline", "Çfarë është dhe nuk është offline"),
    ("offline_maps_available",
     "Αναζήτηση, δρομολόγια, στάσεις, συντεταγμένες και χάραξη διαδρομής λειτουργούν εκτός σύνδεσης.",
     "Search, journeys, stops, coordinates and route shapes all work offline.",
     "Kërkimi, udhëtimet, ndalesat, koordinatat dhe format e itinerarit funksionojnë offline."),
    ("offline_maps_unavailable",
     "Το υπόβαθρο χάρτη δεν κατεβαίνει. Χωρίς σύνδεση ο χάρτης δεν σχεδιάζεται.",
     "The map background is not downloaded. With no connection the map will not draw.",
     "Sfondi i hartës nuk shkarkohet. Pa lidhje harta nuk vizatohet."),
    ("offline_pack_installed", "Εγκατεστημένο", "Installed", "I instaluar"),
    ("offline_pack_not_installed", "Δεν έχει ληφθεί", "Not downloaded", "Pa shkarkuar"),
    ("offline_pack_update_available", "Διαθέσιμη ενημέρωση", "Update available",
     "Përditësim i disponueshëm"),
    ("offline_download_all", "Λήψη όλων", "Download all", "Shkarko të gjitha"),
    ("offline_progress", "%1$d%% από %2$s", "%1$d%% of %2$s", "%1$d%% nga %2$s"),
    ("offline_phase_queued", "Σε αναμονή", "Waiting", "Në pritje"),
    ("offline_phase_downloading", "Κατεβαίνει", "Downloading", "Po shkarkohet"),
    ("offline_phase_resuming", "Συνεχίζει από όπου σταμάτησε", "Resuming where it stopped",
     "Vazhdon nga ku ndaloi"),
    ("offline_phase_verifying", "Έλεγχος ακεραιότητας", "Checking integrity",
     "Kontroll i integritetit"),
    ("offline_phase_installing", "Εγκατάσταση", "Installing", "Po instalohet"),
    ("offline_phase_done", "Ολοκληρώθηκε", "Done", "Përfundoi"),
    ("offline_cancelled", "Η λήψη ακυρώθηκε. Τα κατεβασμένα κομμάτια κρατήθηκαν.",
     "The download was cancelled. What had arrived was kept.",
     "Shkarkimi u anulua. Ajo që kishte mbërritur u mbajt."),
    ("offline_failed_digest",
     "Το αρχείο δεν ταίριαξε με το δημοσιευμένο άθροισμα ελέγχου και απορρίφθηκε. Δεν εγκαταστάθηκε τίποτα.",
     "The file did not match its published checksum and was refused. Nothing was installed.",
     "Skedari nuk përputhej me kontrollin e publikuar dhe u refuzua. Nuk u instalua asgjë."),
    ("offline_failed_release",
     "Το αρχείο ανήκει σε άλλη έκδοση δεδομένων και απορρίφθηκε.",
     "The file belongs to a different data release and was refused.",
     "Skedari i përket një publikimi tjetër dhe u refuzua."),
    ("offline_failed_network", "Δεν υπάρχει σύνδεση για τη λήψη.",
     "There is no connection to download.", "Nuk ka lidhje për shkarkim."),
    ("offline_failed_missing", "Αυτή η έκδοση δεν περιλαμβάνει αυτό το αρχείο.",
     "This release does not publish that file.",
     "Ky publikim nuk e publikon atë skedar."),
    ("offline_delete_pack", "Διαγραφή αρχείου", "Delete this file", "Fshi këtë skedar"),
    ("offline_rollback", "Επιστροφή στην προηγούμενη έκδοση",
     "Go back to the previous release", "Kthehu te publikimi i mëparshëm"),
    ("offline_rollback_to", "Προηγούμενη έκδοση: %1$s", "Previous release: %1$s",
     "Publikimi i mëparshëm: %1$s"),
    ("offline_rollback_none", "Δεν υπάρχει προηγούμενη έκδοση για επιστροφή.",
     "There is no previous release to go back to.",
     "Nuk ka publikim të mëparshëm për të kthehesh."),
    ("offline_rollback_done", "Επιστροφή στην έκδοση %1$s.", "Went back to release %1$s.",
     "U kthye te publikimi %1$s."),
    ("offline_manifest_unreachable",
     "Δεν μπορεί να ελεγχθεί αν υπάρχει νεότερη έκδοση τώρα. Τα εγκατεστημένα λειτουργούν.",
     "Whether a newer release exists cannot be checked right now. What is installed still works.",
     "Nuk mund të kontrollohet tani nëse ka publikim më të ri. Ajo që është instaluar funksionon."),
    ("offline_journeys_pack_note",
     "Τα δρομολόγια κατεβαίνουν ανά ημέρα, μόνο για τις ημέρες που ζητάς.",
     "Journeys are downloaded one day at a time, only for the days you ask for.",
     "Udhëtimet shkarkohen ditë pas dite, vetëm për ditët që kërkon."),
    ("offline_gtfs_note",
     "Το αρχείο GTFS είναι για άλλα εργαλεία. Η εφαρμογή δεν το διαβάζει.",
     "The GTFS archive is for other tools. The application does not read it.",
     "Arkivi GTFS është për mjete të tjera. Aplikacioni nuk e lexon."),

    # -- Travel wallet ----------------------------------------------------------
    ("wallet_title", "Πορτοφόλι ταξιδιού", "Travel wallet", "Portofoli i udhëtimit"),
    ("wallet_body",
     "Κρατά εισιτήρια που εισάγεις εσύ. Αποθηκεύονται κρυπτογραφημένα σε αυτή τη συσκευή και δεν στέλνονται πουθενά.",
     "Holds tickets you import yourself. They are stored encrypted on this device and are never sent anywhere.",
     "Mban bileta që i importon vetë. Ruhen të enkriptuara në këtë pajisje dhe nuk dërgohen kurrë."),
    ("wallet_import", "Εισαγωγή εισιτηρίου", "Import a ticket", "Importo një biletë"),
    ("wallet_empty_title", "Δεν έχεις εισιτήρια εδώ", "No tickets here yet",
     "Pa bileta këtu"),
    ("wallet_empty_body",
     "Διάλεξε ένα αρχείο PDF ή εικόνα από τη συσκευή σου. Δεν ζητάμε πρόσβαση σε όλα τα αρχεία σου.",
     "Choose a PDF or an image from your device. We do not ask for access to all your files.",
     "Zgjidh një PDF ose imazh nga pajisja. Nuk kërkojmë akses në të gjithë skedarët."),
    ("wallet_stored_note",
     "Αποθηκευμένο κρυπτογραφημένα. Δεν συμπεριλαμβάνεται σε αντίγραφα ασφαλείας.",
     "Stored encrypted. Never included in a backup.",
     "Ruajtur të enkriptuar. Nuk përfshihet kurrë në rezervë."),
    ("wallet_never_uploaded",
     "Δεν ανεβαίνει, δεν καταγράφεται και δεν εμφανίζεται σε ειδοποίηση.",
     "Never uploaded, never logged, never put in a notification.",
     "Nuk ngarkohet, nuk regjistrohet, nuk vendoset në njoftim."),
    ("wallet_invalid_type",
     "Επιτρέπονται μόνο PDF, PNG και JPEG. Αυτό το αρχείο δεν εισήχθη.",
     "Only PDF, PNG and JPEG are allowed. That file was not imported.",
     "Lejohen vetëm PDF, PNG dhe JPEG. Ai skedar nuk u importua."),
    ("wallet_too_large", "Το αρχείο είναι πάνω από %1$s και δεν εισήχθη.",
     "The file is larger than %1$s and was not imported.",
     "Skedari është më i madh se %1$s dhe nuk u importua."),
    ("wallet_import_failed", "Το αρχείο δεν μπόρεσε να διαβαστεί.",
     "The file could not be read.", "Skedari nuk mund të lexohej."),
    ("wallet_delete", "Διαγραφή εισιτηρίου", "Delete this ticket", "Fshi këtë biletë"),
    ("wallet_delete_confirm",
     "Θα διαγραφεί οριστικά από αυτή τη συσκευή. Δεν υπάρχει αντίγραφο.",
     "It will be permanently deleted from this device. There is no copy.",
     "Do të fshihet përgjithmonë nga kjo pajisje. Nuk ka kopje."),
    ("wallet_open_ticket", "Άνοιγμα εισιτηρίου", "Open this ticket", "Hap këtë biletë"),
    ("wallet_hide_ticket", "Απόκρυψη", "Hide", "Fshih"),
    ("wallet_imported_at", "Εισήχθη %1$s", "Imported %1$s", "Importuar %1$s"),
    ("wallet_file_size", "Μέγεθος %1$s", "Size %1$s", "Madhësia %1$s"),
    ("wallet_barcode_warning",
     "Κράτα την οθόνη μακριά από φωτογραφικές μηχανές. Ένας κωδικός εισιτηρίου μπορεί να αντιγραφεί.",
     "Keep the screen away from cameras. A ticket code can be copied.",
     "Mbaje ekranin larg kamerave. Një kod bilete mund të kopjohet."),
    ("wallet_locked_note",
     "Το εισιτήριο κλείνει όταν φύγεις από την εφαρμογή και ζητείται ξανά.",
     "The ticket closes when you leave the application and has to be opened again.",
     "Bileta mbyllet kur largohesh nga aplikacioni dhe duhet hapur përsëri."),

    # -- Reminders --------------------------------------------------------------
    ("reminders_title", "Υπενθυμίσεις", "Reminders", "Kujtesa"),
    ("reminders_body",
     "Μια τοπική υπενθύμιση πριν την αναχώρηση. Δεν στέλνεται τίποτα σε κανέναν διακομιστή.",
     "A local reminder before departure. Nothing is sent to any server.",
     "Një kujtesë lokale para nisjes. Asgjë nuk dërgohet në ndonjë server."),
    ("reminders_enable", "Υπενθύμιση για αυτό το ταξίδι", "Remind me about this trip",
     "Kujtomë për këtë udhëtim"),
    ("reminders_lead_label", "Πόσο πριν", "How long before", "Sa kohë përpara"),
    ("reminders_lead_minutes", "%1$d λεπτά πριν", "%1$d minutes before",
     "%1$d minuta përpara"),
    ("reminders_permission_title", "Χρειάζεται άδεια ειδοποιήσεων",
     "Notification permission is needed", "Nevojitet leja e njoftimeve"),
    ("reminders_permission_body",
     "Για να εμφανιστεί η υπενθύμιση χρειάζεται άδεια ειδοποιήσεων. Ζητείται μόνο τώρα που τη ζήτησες.",
     "A reminder can only appear with notification permission. It is asked for only now that you wanted one.",
     "Një kujtesë mund të shfaqet vetëm me leje njoftimi. Kërkohet vetëm tani që e dëshironi."),
    ("reminders_permission_grant", "Δώσε άδεια", "Allow notifications", "Lejo njoftimet"),
    ("reminders_permission_denied",
     "Χωρίς άδεια δεν εμφανίζεται υπενθύμιση. Το ταξίδι παραμένει αποθηκευμένο.",
     "Without permission no reminder appears. The trip stays saved.",
     "Pa leje nuk shfaqet kujtesë. Udhëtimi mbetet i ruajtur."),
    ("reminders_permission_revoked",
     "Η άδεια ειδοποιήσεων ανακλήθηκε, άρα οι υπενθυμίσεις ακυρώθηκαν.",
     "Notification permission was withdrawn, so the reminders were cancelled.",
     "Leja e njoftimeve u tërhoq, kështu që kujtesat u anuluan."),
    ("reminders_permission_settings", "Άνοιγμα ρυθμίσεων εφαρμογής",
     "Open application settings", "Hap cilësimet e aplikacionit"),
    ("reminders_scheduled", "Υπενθύμιση στις %1$s", "Reminder at %1$s", "Kujtesë në %1$s"),
    ("reminders_cancelled", "Η υπενθύμιση ακυρώθηκε.", "The reminder was cancelled.",
     "Kujtesa u anulua."),
    ("reminders_in_the_past",
     "Η ώρα υπενθύμισης έχει περάσει, άρα δεν προγραμματίστηκε.",
     "The reminder time has already passed, so nothing was scheduled.",
     "Ora e kujtesës ka kaluar, kështu që nuk u planifikua asgjë."),
    ("reminders_timezone_changed",
     "Η ζώνη ώρας άλλαξε, άρα οι υπενθυμίσεις υπολογίστηκαν ξανά σε ώρα Ελλάδας.",
     "The time zone changed, so the reminders were recalculated in Greek time.",
     "Zona kohore ndryshoi, kështu që kujtesat u rikalkuluan në kohën greke."),
    ("reminders_privacy_note",
     "Η ειδοποίηση δείχνει μόνο τον σταθμό και την ώρα. Ποτέ όνομα, κωδικό κράτησης ή εισιτήριο.",
     "A notification shows only the terminal and the time. Never a name, a booking reference or a ticket.",
     "Njoftimi tregon vetëm terminalin dhe orën. Kurrë emër, referencë rezervimi ose biletë."),
    ("reminder_notification_title", "Αναχώρηση σε %1$d λεπτά",
     "Departure in %1$d minutes", "Nisja pas %1$d minutash"),
    ("reminder_notification_body", "%1$s, ώρα %2$s", "%1$s at %2$s", "%1$s në %2$s"),
    ("reminder_channel_name", "Υπενθυμίσεις αναχώρησης", "Departure reminders",
     "Kujtesat e nisjes"),
    ("reminder_channel_description",
     "Τοπικές υπενθυμίσεις για ταξίδια που αποθήκευσες.",
     "Local reminders for trips you saved.",
     "Kujtesa lokale për udhëtimet që ruajtët."),

    # -- Settings ---------------------------------------------------------------
    ("settings_title", "Ρυθμίσεις", "Settings", "Cilësimet"),
    ("settings_language", "Γλώσσα", "Language", "Gjuha"),
    ("language_el", "Ελληνικά", "Greek", "Greqisht"),
    ("language_en", "Αγγλικά", "English", "Anglisht"),
    ("language_sq", "Αλβανικά", "Albanian", "Shqip"),
    ("settings_appearance", "Εμφάνιση", "Appearance", "Pamja"),
    ("appearance_system", "Όπως το σύστημα", "Follow the system", "Sipas sistemit"),
    ("appearance_light", "Φωτεινό", "Light", "E ndritshme"),
    ("appearance_dark", "Σκοτεινό", "Dark", "E errët"),
    ("settings_accessibility", "Προσβασιμότητα", "Accessibility", "Aksesueshmëria"),
    ("settings_larger_targets", "Μεγαλύτερα σημεία αφής", "Larger touch targets",
     "Objektiva më të mëdha"),
    ("settings_larger_targets_help",
     "Αυξάνει τα σημεία αφής και τα διαστήματα, ανεξάρτητα από το μέγεθος γραμματοσειράς του συστήματος.",
     "Increases touch targets and spacing, independently of the system font size.",
     "Rrit objektivat dhe hapësirat, pavarësisht nga madhësia e shkrimit të sistemit."),
    ("settings_reduce_motion", "Λιγότερη κίνηση", "Reduce motion", "Zvogëlo lëvizjen"),
    ("settings_reduce_motion_help",
     "Καταργεί τις μεταβάσεις. Τιμάται και η ρύθμιση του συστήματος.",
     "Removes transitions. The system setting is honoured as well.",
     "Heq tranzicionet. Respektohet edhe cilësimi i sistemit."),
    ("settings_expand_stops", "Πλήρης λίστα στάσεων πάντα ανοιχτή",
     "Always expand the full stop list", "Hap gjithmonë listën e plotë të ndalesave"),
    ("settings_offline_storage", "Αποθήκευση εκτός σύνδεσης", "Offline storage",
     "Ruajtja offline"),
    ("settings_download_metered", "Λήψη και με δεδομένα κινητής",
     "Download over mobile data too", "Shkarko edhe me të dhëna mobile"),
    ("settings_privacy", "Ιδιωτικότητα", "Privacy", "Privatësia"),
    ("settings_privacy_body",
     "Χωρίς λογαριασμό, χωρίς αναλυτικά, χωρίς παρακολούθηση, χωρίς διαφημιστικά αναγνωριστικά. Ό,τι αποθηκεύεται μένει σε αυτή τη συσκευή.",
     "No account, no analytics, no tracking, no advertising identifiers. Everything stored stays on this device.",
     "Pa llogari, pa analitikë, pa gjurmim, pa identifikues reklamash. Çdo gjë e ruajtur mbetet në këtë pajisje."),
    ("settings_notifications", "Ειδοποιήσεις", "Notifications", "Njoftimet"),
    ("settings_data_sources", "Πηγές δεδομένων", "Data sources", "Burimet e të dhënave"),
    ("settings_support", "Υποστήριξη", "Support", "Mbështetja"),
    ("settings_support_body", "Στείλε μήνυμα στο %1$s", "Write to %1$s", "Shkruaj në %1$s"),
    ("settings_licences", "Άδειες", "Licences", "Licencat"),
    ("settings_about", "Σχετικά", "About", "Rreth"),
    ("settings_about_mark",
     "Το σήμα είναι ένας κύκλος που τον διασχίζει ένας δρόμος προς ένα πορτοκαλί σημείο: η διαδρομή και ο προορισμός της.",
     "The mark is a ring crossed by a road that leads to an orange point: the journey, and where it takes you.",
     "Shenja është një rreth që e përshkon një rrugë drejt një pike portokalli: udhëtimi dhe vendi ku të çon."),
    ("settings_about_name",
     "Το Odivrelo είναι εφευρημένο όνομα. Δεν είναι ελληνική λέξη και δεν είναι μετάφραση κάποιας λέξης.",
     "Odivrelo is an invented name. It is not a Greek word, and it is not a translation of anything.",
     "Odivrelo është emër i shpikur. Nuk është fjalë greke dhe nuk është përkthim i ndonjë fjale."),
    ("settings_version", "Έκδοση", "Version", "Versioni"),
    ("settings_commit", "Commit", "Commit", "Commit"),
    ("settings_release_id", "Ταυτότητα έκδοσης δεδομένων", "Data release id",
     "Identiteti i publikimit"),
    ("settings_diagnostics", "Διαγνωστικά", "Diagnostics", "Diagnostikë"),
    ("settings_data_mode", "Λειτουργία δεδομένων", "Data mode", "Mënyra e të dhënave"),
    ("data_mode_demo", "Επίδειξη", "Demonstration", "Demonstrim"),
    ("data_mode_real", "Πραγματικά", "Real", "Reale"),
    ("data_mode_help",
     "Στη λειτουργία επίδειξης εμφανίζεται μόνιμη ειδοποίηση ότι τα δεδομένα είναι επινοημένα.",
     "In demonstration mode a permanent notice says the data is invented.",
     "Në mënyrën e demonstrimit një vërejtje e përhershme thotë që të dhënat janë të trilluara."),

    # -- Sources, licences, diagnostics ----------------------------------------
    ("sources_title", "Πηγές δεδομένων", "Data sources", "Burimet e të dhënave"),
    ("sources_body",
     "Κάθε πηγή με την κατάσταση δικαιωμάτων και την άδειά της.",
     "Every source with its rights status and licence.",
     "Çdo burim me statusin e të drejtave dhe licencën."),
    ("rights_allowed", "Επιτρέπεται η χρήση", "Reuse allowed", "Ripërdorimi lejohet"),
    ("rights_permission_pending", "Αναμονή άδειας", "Permission pending",
     "Në pritje të lejes"),
    ("rights_prohibited", "Δεν επιτρέπεται", "Not allowed", "Nuk lejohet"),
    ("rights_unknown", "Άγνωστο", "Unknown", "I panjohur"),
    ("rights_unknown_help",
     "Άγνωστη κατάσταση δικαιωμάτων σημαίνει ότι δεν επιτρέπεται η χρήση, όχι ότι επιτρέπεται.",
     "An unknown rights status means reuse is not permitted, not that it is.",
     "Status i panjohur i të drejtave do të thotë që ripërdorimi nuk lejohet, jo që lejohet."),
    ("sources_licence", "Άδεια: %1$s", "Licence: %1$s", "Licenca: %1$s"),
    ("sources_retrieved", "Ανακτήθηκε %1$s", "Retrieved %1$s", "Marrë %1$s"),
    ("licences_title", "Άδειες", "Licences", "Licencat"),
    ("licences_body",
     "Το Odivrelo χρησιμοποιεί βιβλιοθήκες ανοιχτού κώδικα και δημόσια δεδομένα.",
     "Odivrelo uses open source libraries and public data.",
     "Odivrelo përdor biblioteka me kod të hapur dhe të dhëna publike."),
    ("diagnostics_title", "Διαγνωστικά", "Diagnostics", "Diagnostikë"),
    ("diagnostics_body",
     "Τεχνικές πληροφορίες για αναφορά προβλήματος. Δεν περιλαμβάνουν προσωπικά δεδομένα, εισιτήρια ή μυστικά.",
     "Technical information for a bug report. It contains no personal data, no ticket and no secret.",
     "Informacion teknik për një raport. Nuk përmban të dhëna personale, biletë ose sekret."),
    ("diagnostics_copied", "Αντιγράφηκε.", "Copied.", "Kopjuar."),
    ("diagnostics_window", "Παράθυρο", "Window", "Dritarja"),
    ("diagnostics_posture", "Στάση συσκευής", "Device posture", "Pozicioni i pajisjes"),
    ("diagnostics_packs", "Εγκατεστημένα αρχεία", "Installed files",
     "Skedarë të instaluar"),

    # -- Adaptive and posture ---------------------------------------------------
    ("posture_flat", "Επίπεδη", "Flat", "E sheshtë"),
    ("posture_half_open", "Μισάνοιχτη", "Half open", "Gjysmë e hapur"),
    ("posture_book", "Σαν βιβλίο", "Book", "Si libër"),
    ("posture_tabletop", "Σαν τραπέζι", "Tabletop", "Si tavolinë"),
    ("posture_none", "Χωρίς άρθρωση", "No hinge", "Pa bashkim"),
    ("window_compact", "Στενό", "Compact", "I ngushtë"),
    ("window_medium", "Μέτριο", "Medium", "I mesëm"),
    ("window_expanded", "Ευρύ", "Expanded", "I gjerë"),

    # -- Deep links -------------------------------------------------------------
    ("deeplink_unknown_title", "Ο σύνδεσμος δεν αναγνωρίζεται",
     "That link is not recognised", "Ajo lidhje nuk njihet"),
    ("deeplink_unknown_body",
     "Ο σύνδεσμος δεν αντιστοιχεί σε κάτι σε αυτή την εφαρμογή. Ξεκίνα από την αναζήτηση.",
     "The link does not point at anything in this application. Start from search.",
     "Lidhja nuk tregon asgjë në këtë aplikacion. Fillo nga kërkimi."),
    ("deeplink_expired_title", "Ο σύνδεσμος αφορά περασμένη ημέρα",
     "That link is for a day that has passed", "Ajo lidhje është për një ditë që kaloi"),
    ("deeplink_expired_body", "Άνοιξε την αναζήτηση για σημερινή ημερομηνία.",
     "Open search for a current date.", "Hap kërkimin për një datë aktuale."),
    ("deeplink_foreign_host_title", "Ο σύνδεσμος δεν ανήκει στο Odivrelo",
     "That link is not a Odivrelo link", "Ajo lidhje nuk është e Odivrelo"),

    # -- Accessibility descriptions --------------------------------------------
    ("a11y_app_mark",
     "Σήμα Odivrelo: κύκλος που τον διασχίζει δρόμος, με πορτοκαλί σημείο προορισμού",
     "Odivrelo mark: a ring crossed by a road, with an orange destination point",
     "Shenja Odivrelo: një rreth i përshkuar nga një rrugë, me një pikë portokalli destinacioni"),
    ("a11y_journey_summary",
     "%1$s, αναχώρηση %2$s από %3$s, άφιξη %4$s στο %5$s, διάρκεια %6$s",
     "%1$s, departs %2$s from %3$s, arrives %4$s at %5$s, %6$s",
     "%1$s, niset %2$s nga %3$s, mbërrin %4$s në %5$s, %6$s"),
    ("a11y_expand", "Άνοιγμα", "Expand", "Zgjero"),
    ("a11y_collapse", "Σύμπτυξη", "Collapse", "Zvogëlo"),
    ("a11y_selected", "Επιλεγμένο", "Selected", "Zgjedhur"),
    ("a11y_error_announced", "Σφάλμα: %1$s", "Error: %1$s", "Gabim: %1$s"),
    ("a11y_progress", "Πρόοδος %1$d τοις εκατό", "Progress %1$d percent",
     "Progresi %1$d përqind"),
    ("a11y_stop_sequence", "Στάση %1$d από %2$d", "Stop %1$d of %2$d",
     "Ndalesa %1$d nga %2$d"),
    ("a11y_close_detail", "Κλείσιμο λεπτομερειών", "Close the detail",
     "Mbyll detajet"),
]


def xml_for(index: int, language: str) -> str:
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!--",
        "  Odivrelo user-visible text, " + language + ".",
        "",
        "  All three languages carry exactly the same keys. A unit test",
        "  (LocalisationCompletenessTest) fails the build if one of them is missing a",
        "  key, has an empty value, or disagrees about format arguments, so a",
        "  half-translated release cannot ship.",
        "-->",
        '<resources xmlns:tools="http://schemas.android.com/tools" tools:ignore="MissingTranslation">',
    ]
    for row in S:
        key = row[0]
        value = row[index]
        if not value:
            raise SystemExit("empty value for " + key + " in " + language)
        escaped = html.escape(value, quote=False).replace("'", "\\'")
        lines.append('    <string name="' + key + '">' + escaped + "</string>")
    lines.append("</resources>")
    return "\n".join(lines) + "\n"


keys = [row[0] for row in S]
if len(keys) != len(set(keys)):
    duplicates = sorted({k for k in keys if keys.count(k) > 1})
    raise SystemExit("duplicate keys: " + ", ".join(duplicates))

targets = [
    (1, "values", "Greek (the default language)"),
    (2, "values-en", "English"),
    (3, "values-sq", "Albanian"),
]
for index, folder, language in targets:
    path = os.path.join(ROOT, "src/main/res", folder, "strings.xml")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(xml_for(index, language))
    print("wrote " + path)
print(str(len(S)) + " keys per language")
