#!/usr/bin/env bash
# Generates every platform's colours from design/tokens/odivrelo.tokens.json.
#
#   bash scripts/generate-design-tokens.sh           # write
#   bash scripts/generate-design-tokens.sh --check   # fail if anything is stale
#
# One palette, three platforms:
#
#   design/tokens/odivrelo.css                      reference stylesheet
#   apps/web/src/styles/tokens.css                  the @generated colour blocks
#   apps/web/index.html                             theme-color and boot colours
#   apps/web/src/styles/brandColors.generated.ts    colours a script needs (the map)
#   apps/android/.../theme/OdivreloPalette.kt       Compose semantic colours
#   apps/android/src/main/res/values*/colors.xml    colours needed before Compose
#   apps/ios/Odivrelo/Generated/Theme.swift         via scripts/ios-generate-theme.sh
#
# Before writing anything it audits WCAG 2.1 contrast for every pairing the
# products draw text or controls with, in both themes, and exits non-zero if a
# pairing falls below AA. Orange is an accent: it is only ever audited as a
# fill behind dark ink, never as text on a light surface.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODE="${1:-write}"

/usr/bin/env python3 - "${REPO_ROOT}" "${MODE}" <<'PY'
import json, pathlib, re, sys

root = pathlib.Path(sys.argv[1])
mode = sys.argv[2]
tokens = json.loads((root / "design/tokens/odivrelo.tokens.json").read_text(encoding="utf-8"))
colour = tokens["color"]
prim = colour["primitive"]
REF = re.compile(r"^\{color\.primitive\.([A-Za-z0-9]+)\}$")


def resolve(v):
    m = REF.match(v)
    return (prim[m.group(1)]["$value"] if m else v).upper()


light = {k: resolve(v["$value"]) for k, v in colour["light"].items()}
dark = {k: resolve(v["$value"]) for k, v in colour["dark"].items()}
brand = {k: v["$value"].upper() for k, v in colour["brand"].items()}
if set(light) != set(dark):
    sys.exit("light and dark semantic palettes must carry the same roles")


# -- contrast audit ---------------------------------------------------------
def lum(h):
    h = h.lstrip("#")
    out = []
    for i in (0, 2, 4):
        c = int(h[i:i + 2], 16) / 255
        out.append(c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4)
    return 0.2126 * out[0] + 0.7152 * out[1] + 0.0722 * out[2]


def ratio(a, b):
    la, lb = sorted((lum(a), lum(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


TEXT = 4.5   # body text, AA
UI = 3.0     # focus indicators and control boundaries, AA non-text
PAIRS = [
    ("textPrimary", "background", TEXT), ("textPrimary", "surface", TEXT),
    ("textPrimary", "surfaceMuted", TEXT), ("textPrimary", "neutralSurface", TEXT),
    ("textPrimary", "surfaceContainerHigh", TEXT), ("textPrimary", "surfaceContainerHighest", TEXT),
    ("textSecondary", "background", TEXT), ("textSecondary", "surface", TEXT),
    ("textSecondary", "surfaceMuted", TEXT), ("textSecondary", "neutralSurface", TEXT),
    ("primary", "background", TEXT), ("primary", "surface", TEXT), ("primary", "surfaceMuted", TEXT),
    ("onPrimary", "primary", TEXT), ("onPrimary", "primaryPressed", TEXT),
    ("primaryInk", "primarySoft", TEXT),
    ("accentInk", "accent", TEXT),
    ("warningText", "warningSurface", TEXT), ("errorText", "errorSurface", TEXT),
    ("successText", "successSurface", TEXT), ("infoText", "infoSurface", TEXT),
    ("errorText", "surface", TEXT),
    ("focusRing", "background", UI), ("focusRing", "surface", UI),
    ("borderStrong", "surface", UI), ("outline", "surface", UI),
]
failures, report = [], []
for theme, pal in (("light", light), ("dark", dark)):
    for fg, bg, need in PAIRS:
        r = ratio(pal[fg], pal[bg])
        report.append(f"  {theme:5} {fg:>14} on {bg:<24} {r:5.2f}:1  (needs {need})")
        if r < need:
            failures.append(f"{theme}: {fg} {pal[fg]} on {bg} {pal[bg]} is {r:.2f}:1, needs {need}:1")
# The brand pairs the logo and icons use.
for fg, bg, need in (("deepTealBlue", "lightBackground", UI), ("navy", "lightBackground", TEXT),
                     ("warmOrange", "deepTealBlue", UI)):
    r = ratio(brand[fg], brand[bg])
    report.append(f"  brand {fg:>14} on {bg:<24} {r:5.2f}:1  (needs {need})")
    if r < need:
        failures.append(f"brand: {fg} on {bg} is {r:.2f}:1, needs {need}:1")
if failures:
    print("\n".join(report))
    sys.exit("contrast audit failed:\n  " + "\n  ".join(failures))


def kebab(name):
    return re.sub(r"([A-Z])", lambda m: "-" + m.group(1).lower(), name)


def css_block(pal, indent):
    return "\n".join(f"{indent}--od-{kebab(k)}: {v.lower()};" for k, v in pal.items())


outputs = {}

# -- design/tokens/odivrelo.css ---------------------------------------------
space = tokens["space"]; radius = tokens["radius"]; size = tokens["size"]; motion = tokens["motion"]
lines = [
    "/* Generated by scripts/generate-design-tokens.sh from odivrelo.tokens.json. */",
    ":root {", "  color-scheme: light;", css_block(light, "  "),
    f"  --od-brand-deep-teal-blue: {brand['deepTealBlue'].lower()};",
    f"  --od-brand-warm-orange: {brand['warmOrange'].lower()};",
    f"  --od-brand-light-background: {brand['lightBackground'].lower()};",
    f"  --od-brand-navy: {brand['navy'].lower()};",
]
lines += [f"  --od-radius-{k}: {v['$value']};" for k, v in radius.items()]
lines += [f"  --od-space-{k}: {v['$value']};" for k, v in space.items() if k != "0"]
lines += [
    f"  --od-touch-minimum: {size['touchMinimum']['$value']};",
    f"  --od-control-height: {size['control']['$value']};",
    f"  --od-content-maximum: {size['contentMaximum']['$value']};",
    '  --od-font-sans: Inter, "SF Pro Text", Roboto, system-ui, sans-serif;',
    "  --od-shadow-card: 0 6px 18px rgb(8 47 69 / 8%);",
    "  --od-shadow-floating: 0 12px 32px rgb(8 47 69 / 14%);",
]
lines += [f"  --od-motion-{k}: {v['$value']};" for k, v in motion.items() if k != "easing"]
e = motion["easing"]["$value"]
lines += [f"  --od-easing: cubic-bezier({e[0]}, {e[1]}, {e[2]}, {e[3]});", "}", "",
          "@media (prefers-color-scheme: dark) {", "  :root {", "    color-scheme: dark;",
          css_block(dark, "    "), "  }", "}", "",
          "@media (prefers-reduced-motion: reduce) {", "  :root {"]
lines += [f"    --od-motion-{k}: 0ms;" for k in motion if k != "easing"]
lines += ["  }", "}", ""]
outputs[root / "design/tokens/odivrelo.css"] = "\n".join(lines)


# -- marker rewrites --------------------------------------------------------
def between(text, name, body, comment=("/*", "*/")):
    o, c = comment
    pattern = re.compile(
        r"(?P<indent>[ \t]*)" + re.escape(f"{o} @generated {name} start") + r"(?P<rest>[^\n]*)\n"
        r".*?" + r"[ \t]*" + re.escape(f"{o} @generated {name} end {c}"),
        re.S,
    )
    count = 0

    def repl(m):
        nonlocal count
        count += 1
        ind = m.group("indent")
        block = "\n".join(ind + line if line else line for line in body(ind).splitlines())
        return (f"{ind}{o} @generated {name} start{m.group('rest')}\n" + (block + "\n" if block else "")
                + f"{ind}{o} @generated {name} end {c}")

    new = pattern.sub(repl, text)
    if count == 0:
        sys.exit(f"marker '@generated {name}' not found")
    return new


web_css = root / "apps/web/src/styles/tokens.css"
text = web_css.read_text(encoding="utf-8")
text = between(text, "colours:light", lambda ind: css_block(light, "") + "\n" + "\n".join([
    f"--od-brand-deep-teal-blue: {brand['deepTealBlue'].lower()};",
    f"--od-brand-warm-orange: {brand['warmOrange'].lower()};",
    f"--od-brand-light-background: {brand['lightBackground'].lower()};",
    f"--od-brand-navy: {brand['navy'].lower()};",
]))
text = between(text, "colours:dark", lambda ind: css_block(dark, ""))
outputs[web_css] = text

index = root / "apps/web/index.html"
text = index.read_text(encoding="utf-8")
text = between(text, "theme-color", lambda ind: "\n".join([
    f'<meta name="theme-color" media="(prefers-color-scheme: light)" content="{brand["deepTealBlue"].lower()}" />',
    f'<meta name="theme-color" media="(prefers-color-scheme: dark)" content="{dark["background"].lower()}" />',
]), comment=("<!--", "-->"))
bl, fl = light["background"].lower(), light["textPrimary"].lower()
bd, fd = dark["background"].lower(), dark["textPrimary"].lower()
text = between(text, "boot-colours", lambda ind: "\n".join([
    f":root {{ color-scheme: light; --od-boot-bg: {bl}; --od-boot-fg: {fl}; }}",
    "@media (prefers-color-scheme: dark) {",
    f"  :root:not([data-theme='light']) {{ color-scheme: dark; --od-boot-bg: {bd}; --od-boot-fg: {fd}; }}",
    "}",
    f":root[data-theme='dark'] {{ color-scheme: dark; --od-boot-bg: {bd}; --od-boot-fg: {fd}; }}",
]))
outputs[index] = text

ts = ["// GENERATED FILE. Do not edit by hand.",
      "// Source: design/tokens/odivrelo.tokens.json via scripts/generate-design-tokens.sh.",
      "//",
      "// For the few places a script, not a stylesheet, needs a colour (the map).",
      "// Everything else reads the --od-* custom properties.",
      "",
      "export const BRAND_COLORS = {"]
ts += [f"  {k}: '{v}'," for k, v in brand.items()]
ts += ["} as const;", "",
       "export const THEME_COLORS = {",
       "  light: {"] + [f"    {k}: '{v}'," for k, v in light.items()] + ["  },", "  dark: {"] + \
      [f"    {k}: '{v}'," for k, v in dark.items()] + ["  },", "} as const;", ""]
outputs[root / "apps/web/src/styles/brandColors.generated.ts"] = "\n".join(ts)

# -- Android ----------------------------------------------------------------
kt = ["// Generated by scripts/generate-design-tokens.sh from design/tokens/odivrelo.tokens.json.",
      "// Do not edit by hand. Re-run the script after changing the design tokens.",
      "",
      "package dev.peterdsp.odivrelo.theme",
      "",
      "import androidx.compose.ui.graphics.Color",
      "",
      "/** The Odivrelo semantic palette, one object per appearance. */",
      "object OdivreloPalette {",
      "    /** Brand colours, identical in both appearances. */",
      "    object Brand {"]
kt += [f"        val {k} = Color(0xFF{v[1:]})" for k, v in brand.items()]
kt += ["    }", ""]
for name, pal in (("Light", light), ("Dark", dark)):
    kt += [f"    object {name} {{"]
    kt += [f"        val {k} = Color(0xFF{v[1:]})" for k, v in pal.items()]
    kt += ["    }", ""]
kt[-1] = "}"
kt.append("")
outputs[root / "apps/android/src/main/kotlin/dev/peterdsp/odivrelo/theme/OdivreloPalette.kt"] = "\n".join(kt)


def colors_xml(window, splash, ring, road):
    return "\n".join([
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!--",
        "  Only the colours the platform needs before Compose starts drawing, and the",
        "  two that tint the in-app mark. Generated by scripts/generate-design-tokens.sh",
        "  from design/tokens/odivrelo.tokens.json; every other colour lives in the",
        "  Compose theme, generated from the same file, so there is one palette.",
        "-->",
        "<resources>",
        "    <!-- color.*.background -->",
        f'    <color name="odivrelo_window_background">{window}</color>',
        "    <!-- color.brand.deepTealBlue, the app icon's ground -->",
        f'    <color name="odivrelo_splash_background">{splash}</color>',
        "    <!-- the in-app mark: ring and road -->",
        f'    <color name="odivrelo_mark_ring">{ring}</color>',
        f'    <color name="odivrelo_mark_road">{road}</color>',
        "</resources>",
        "",
    ])


res = root / "apps/android/src/main/res"
outputs[res / "values/colors.xml"] = colors_xml(light["background"], brand["deepTealBlue"], light["markRing"], light["markRoad"])
outputs[res / "values-night/colors.xml"] = colors_xml(dark["background"], brand["deepTealBlue"], dark["markRing"], dark["markRoad"])

stale = []
for path, content in outputs.items():
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current != content:
        stale.append(path.relative_to(root))
        if mode != "--check":
            path.write_text(content, encoding="utf-8")
if mode == "--check":
    if stale:
        sys.exit("stale generated colours, run scripts/generate-design-tokens.sh:\n  " + "\n  ".join(map(str, stale)))
    print(f"design tokens: {len(outputs)} outputs current, contrast audit passed ({len(report)} pairings)")
else:
    for p in stale:
        print(f"wrote {p}")
    print(f"contrast audit passed ({len(report)} pairings)")
    import os
    if os.environ.get("VERBOSE"):
        print("\n".join(report))
PY

if [[ "${MODE}" != "--check" ]]; then
  bash "${REPO_ROOT}/scripts/ios-generate-theme.sh"
fi
