#!/usr/bin/env bash
# Generates apps/ios/Poravia/Generated/Theme.swift and the brand colour sets in
# the Poravia asset catalog from design/tokens/poravia.tokens.json.
#
# The palette (Aegean teal, limestone, sun amber) is kept exactly as designed.
# Only the identifiers are renamed into the Poravia namespace: no token key,
# type name or asset name in the generated output carries the legacy product
# name. Features consume the semantic layer, never the primitives.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TOKENS="${REPO_ROOT}/design/tokens/poravia.tokens.json"
OUT_FILE="${REPO_ROOT}/apps/ios/Poravia/Generated/Theme.swift"
ASSETS="${REPO_ROOT}/apps/ios/Poravia/Resources/Assets.xcassets"

if [[ ! -f "${TOKENS}" ]]; then
  echo "error: ${TOKENS} not found" >&2
  exit 1
fi

mkdir -p "$(dirname "${OUT_FILE}")" "${ASSETS}"

/usr/bin/env python3 - "${TOKENS}" "${OUT_FILE}" "${ASSETS}" <<'PY'
import json, os, re, sys

tokens_path, out_path, assets_path = sys.argv[1], sys.argv[2], sys.argv[3]
with open(tokens_path, "r", encoding="utf-8") as handle:
    tokens = json.load(handle)

primitives = tokens["color"]["primitive"]
REF = re.compile(r"^\{color\.primitive\.([A-Za-z0-9]+)\}$")


def resolve(value: str) -> str:
    match = REF.match(value)
    if match:
        return primitives[match.group(1)]["$value"]
    return value


def components(hex_value: str):
    text = hex_value.lstrip("#")
    if len(text) == 6:
        text += "FF"
    r, g, b, a = (int(text[i:i + 2], 16) for i in (0, 2, 4, 6))
    return r / 255.0, g / 255.0, b / 255.0, a / 255.0


light = {k: resolve(v["$value"]) for k, v in tokens["color"]["light"].items()}
dark = {k: resolve(v["$value"]) for k, v in tokens["color"]["dark"].items()}
assert set(light) == set(dark), "light and dark semantic palettes must match"
semantic = sorted(light)

space = {k: float(v["$value"].removesuffix("px")) for k, v in tokens["space"].items()}
radius = {k: float(v["$value"].removesuffix("px")) for k, v in tokens["radius"].items()}
size = {k: float(v["$value"].removesuffix("px")) for k, v in tokens["size"].items()}
motion = {k: v for k, v in tokens["motion"].items() if k != "easing"}
easing = tokens["motion"]["easing"]["$value"]

L = []
w = L.append
w("// Generated by scripts/ios-generate-theme.sh from design/tokens/poravia.tokens.json.")
w("// Do not edit by hand. Re-run the script after changing the design tokens.")
w("")
w("import SwiftUI")
w("")
w("/// The Poravia palette, spacing, radius, size and motion scale.")
w("///")
w("/// Colours are dynamic: each semantic role resolves to the light or dark")
w("/// value from the design tokens through the active trait collection, so a")
w("/// single identifier is correct in both appearances.")
w("public enum Theme: Sendable {")
w("    public enum Palette: Sendable {")
for key in semantic:
    lr, lg, lb, la = components(light[key])
    dr, dg, db, da = components(dark[key])
    w(f"        /// Light `{light[key]}` · Dark `{dark[key]}`")
    w(f"        public static let {key} = Color(")
    w(f"            light: (r: {lr:.6f}, g: {lg:.6f}, b: {lb:.6f}, a: {la:.6f}),")
    w(f"            dark: (r: {dr:.6f}, g: {dg:.6f}, b: {db:.6f}, a: {da:.6f})")
    w("        )")
w("")
w("        /// Every semantic role, for contrast auditing and snapshot tests.")
w("        public static let allRoles: [(name: String, light: String, dark: String)] = [")
for key in semantic:
    w(f'            ("{key}", "{light[key].upper()}", "{dark[key].upper()}"),')
w("        ]")
w("    }")
w("")
w("    public enum Space: Sendable {")
names = {"0": "none", "1": "xxSmall", "2": "xSmall", "3": "small", "4": "medium",
         "5": "mediumPlus", "6": "large", "8": "xLarge", "10": "xxLarge",
         "12": "xxxLarge", "16": "huge"}
for key in sorted(space, key=lambda k: int(k)):
    w(f"        public static let {names[key]}: CGFloat = {space[key]:g}")
w("    }")
w("")
w("    public enum Radius: Sendable {")
for key, value in radius.items():
    w(f"        public static let {key}: CGFloat = {value:g}")
w("    }")
w("")
w("    public enum Size: Sendable {")
for key, value in size.items():
    w(f"        public static let {key}: CGFloat = {value:g}")
w("    }")
w("")
w("    public enum Motion: Sendable {")
for key, value in motion.items():
    ms = float(value["$value"].removesuffix("ms"))
    w(f"        public static let {key}: Double = {ms / 1000.0:g}")
w(f"        public static let easing = UnitCurve.bezier(")
w(f"            startControlPoint: UnitPoint(x: {easing[0]}, y: {easing[1]}),")
w(f"            endControlPoint: UnitPoint(x: {easing[2]}, y: {easing[3]})")
w("        )")
w("    }")
w("}")
w("")
w("extension Color {")
w("    /// Builds a colour that resolves per appearance without an asset entry.")
w("    init(")
w("        light: (r: Double, g: Double, b: Double, a: Double),")
w("        dark: (r: Double, g: Double, b: Double, a: Double)")
w("    ) {")
w("        self.init(uiColor: UIColor { traits in")
w("            let c = traits.userInterfaceStyle == .dark ? dark : light")
w("            return UIColor(red: c.r, green: c.g, blue: c.b, alpha: c.a)")
w("        })")
w("    }")
w("}")
w("")

with open(out_path, "w", encoding="utf-8") as handle:
    handle.write("\n".join(L))

# Asset-catalog colour sets used by Info.plist (launch screen) and the tint.
def colorset(name: str, light_hex: str, dark_hex: str) -> None:
    folder = os.path.join(assets_path, f"{name}.colorset")
    os.makedirs(folder, exist_ok=True)

    def entry(hex_value, appearances):
        r, g, b, a = components(hex_value)
        payload = {
            "color": {
                "color-space": "srgb",
                "components": {
                    "alpha": f"{a:.3f}",
                    "blue": f"0x{int(round(b * 255)):02X}",
                    "green": f"0x{int(round(g * 255)):02X}",
                    "red": f"0x{int(round(r * 255)):02X}",
                },
            },
            "idiom": "universal",
        }
        if appearances:
            payload["appearances"] = appearances
        return payload

    contents = {
        "colors": [
            entry(light_hex, None),
            entry(dark_hex, [{"appearance": "luminosity", "value": "dark"}]),
        ],
        "info": {"author": "xcode", "version": 1},
    }
    with open(os.path.join(folder, "Contents.json"), "w", encoding="utf-8") as handle:
        json.dump(contents, handle, indent=2, sort_keys=True)
        handle.write("\n")


colorset("BrandBackground", light["background"], dark["background"])
colorset("AccentColor", light["primary"], dark["primary"])

root_contents = os.path.join(assets_path, "Contents.json")
if not os.path.exists(root_contents):
    with open(root_contents, "w", encoding="utf-8") as handle:
        json.dump({"info": {"author": "xcode", "version": 1}}, handle, indent=2)
        handle.write("\n")

print(f"wrote {out_path}")
print(f"wrote {assets_path}/BrandBackground.colorset, {assets_path}/AccentColor.colorset")
PY
