#!/usr/bin/env bash
# Generates apps/ios/Poravia/Generated/Brand.swift from the repository brand.json.
# brand.json is the single source of product identity. Nothing in the iOS app may
# hardcode the product name, slug, domain, bundle identifier or URL scheme.
#
# `legacyNames` is deliberately not emitted. Compiling the old product names in
# would put them into the shipped binary, which is exactly what
# scripts/check-brand.sh exists to prevent. `BrandIdentityTests` reads them from
# brand.json at test time instead.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BRAND_JSON="${REPO_ROOT}/brand.json"
OUT_DIR="${REPO_ROOT}/apps/ios/Poravia/Generated"
OUT_FILE="${OUT_DIR}/Brand.swift"

if [[ ! -f "${BRAND_JSON}" ]]; then
  echo "error: ${BRAND_JSON} not found" >&2
  exit 1
fi

mkdir -p "${OUT_DIR}"

/usr/bin/env python3 - "${BRAND_JSON}" "${OUT_FILE}" <<'PY'
import json, sys, datetime

brand_path, out_path = sys.argv[1], sys.argv[2]
with open(brand_path, "r", encoding="utf-8") as handle:
    brand = json.load(handle)

def swift_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'

def swift_array(values) -> str:
    return "[" + ", ".join(swift_string(v) for v in values) + "]"

tagline = brand["tagline"]
languages = brand["languages"]

lines = []
lines.append("// Generated by scripts/ios-generate-brand.sh from brand.json.")
lines.append("// Do not edit by hand. Re-run the script after changing brand.json.")
lines.append("")
lines.append("import Foundation")
lines.append("")
lines.append("/// Product identity generated from the repository-wide `brand.json`.")
lines.append("/// Every product-name, slug, domain, bundle-identifier and URL-scheme")
lines.append("/// reference in the iOS application resolves through this enumeration.")
lines.append("public enum Brand: Sendable {")
lines.append(f"    public static let name = {swift_string(brand['name'])}")
lines.append(f"    public static let slug = {swift_string(brand['slug'])}")
lines.append(f"    public static let domain = {swift_string(brand['domain'])}")
lines.append(f"    public static let websiteURLString = {swift_string(brand['url'])}")
lines.append(f"    public static let supportEmail = {swift_string(brand['supportEmail'])}")
lines.append(f"    public static let bundleIdentifier = {swift_string(brand['bundleId'])}")
lines.append(f"    public static let urlScheme = {swift_string(brand['urlScheme'])}")
lines.append(f"    public static let contractVersion = {swift_string(brand['contractVersion'])}")
lines.append(f"    public static let marketingVersion = {swift_string(brand['version'])}")
lines.append(f"    public static let repository = {swift_string(brand['repository'])}")
lines.append(f"    public static let languageTags: [String] = {swift_array(languages)}")
lines.append(f"    public static let defaultLanguageTag = {swift_string(brand['defaultLanguage'])}")
lines.append("")
lines.append("    public static var websiteURL: URL {")
lines.append("        guard let url = URL(string: websiteURLString) else {")
lines.append("            preconditionFailure(\"brand.json carries an invalid url value\")")
lines.append("        }")
lines.append("        return url")
lines.append("    }")
lines.append("")
lines.append("    public static var supportMailURL: URL {")
lines.append("        guard let url = URL(string: \"mailto:\\(supportEmail)\") else {")
lines.append("            preconditionFailure(\"brand.json carries an invalid supportEmail value\")")
lines.append("        }")
lines.append("        return url")
lines.append("    }")
lines.append("")
lines.append("    /// The universal-link prefix the application accepts.")
lines.append("    public static var universalLinkPrefix: String { \"https://\\(domain)\" }")
lines.append("")
lines.append("    /// The associated-domain entitlement value for the controlled domain.")
lines.append("    public static var associatedDomainEntitlement: String { \"applinks:\\(domain)\" }")
lines.append("")
lines.append("    public static func tagline(forLanguageTag tag: String) -> String {")
lines.append("        switch tag {")
for key in languages:
    lines.append(f"        case {swift_string(key)}: return {swift_string(tagline[key])}")
lines.append("        default: return taglineDefault")
lines.append("        }")
lines.append("    }")
lines.append("")
lines.append(f"    public static let taglineDefault = {swift_string(tagline[brand['defaultLanguage']])}")
lines.append("}")
lines.append("")

with open(out_path, "w", encoding="utf-8") as handle:
    handle.write("\n".join(lines))

print(f"wrote {out_path}")
PY
