#!/usr/bin/env bash
# Generates shared/core/src/commonMain/kotlin/dev/peterdsp/odivrelo/core/Brand.kt
# from brand.json. brand.json is the single source of product identity; nothing
# else in shared/ or apps/android/ may hardcode the name, slug, domain or
# applicationId.
#
# Usage: scripts/shared-generate-brand.sh [--check]
#   --check  regenerate into a temporary file and fail if it differs from the
#            committed file (for CI and pre-commit use).
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
brand_json="${repo_root}/brand.json"
out_file="${repo_root}/shared/core/src/commonMain/kotlin/dev/peterdsp/odivrelo/core/Brand.kt"

if [[ ! -f "${brand_json}" ]]; then
  echo "error: ${brand_json} not found" >&2
  exit 1
fi

python_bin=""
for candidate in python3 python; do
  if command -v "${candidate}" >/dev/null 2>&1; then python_bin="${candidate}"; break; fi
done
if [[ -z "${python_bin}" ]]; then
  echo "error: python3 is required to read brand.json" >&2
  exit 1
fi

generate() {
  "${python_bin}" - "${brand_json}" <<'PY'
import json, sys

with open(sys.argv[1], encoding="utf-8") as handle:
    brand = json.load(handle)


def kstr(value):
    if value is None:
        return "null"
    escaped = (
        str(value)
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "\\$")
        .replace("\n", "\\n")
    )
    return '"%s"' % escaped


def klist(values):
    return "listOf(%s)" % ", ".join(kstr(v) for v in values)


def kmap(values):
    return "mapOf(%s)" % ", ".join(
        "%s to %s" % (kstr(k), kstr(v)) for k, v in sorted(values.items())
    )


tagline = brand.get("tagline", {})
languages = brand.get("languages", [])

print('// Generated by scripts/shared-generate-brand.sh from brand.json.')
print('// Do not edit by hand. Re-run the script after changing brand.json.')
print('@file:Suppress("unused")')
print()
print("package dev.peterdsp.odivrelo.core")
print()
print("import kotlin.native.ObjCName")
print()
print('/**')
print(' * Product identity, generated from the repository-level brand.json.')
print(' *')
print(' * The invented product name is suggested by the Greek word for a passage,')
print(' * ford or strait. It is not itself a Greek word and carries no verified')
print(' * translation.')
print(' */')
print('@ObjCName("OdivreloBrand")')
print("object Brand {")
print("    const val NAME: String = %s" % kstr(brand.get("name")))
print("    const val SLUG: String = %s" % kstr(brand.get("slug")))
print("    const val DOMAIN: String = %s" % kstr(brand.get("domain")))
print("    const val URL: String = %s" % kstr(brand.get("url")))
print("    const val SUPPORT_EMAIL: String = %s" % kstr(brand.get("supportEmail")))
print("    const val BUNDLE_ID: String = %s" % kstr(brand.get("bundleId")))
print("    const val ANDROID_APPLICATION_ID: String = %s" % kstr(brand.get("androidApplicationId")))
print("    const val ANDROID_PACKAGE: String = %s" % kstr(brand.get("androidPackage")))
print("    const val URL_SCHEME: String = %s" % kstr(brand.get("urlScheme")))
print("    const val ENV_PREFIX: String = %s" % kstr(brand.get("envPrefix")))
print("    const val CONTRACT_VERSION: String = %s" % kstr(brand.get("contractVersion")))
print("    const val VERSION: String = %s" % kstr(brand.get("version")))
print("    const val REPOSITORY: String = %s" % kstr(brand.get("repository")))
print("    const val DEFAULT_LANGUAGE: String = %s" % kstr(brand.get("defaultLanguage")))
print()
print("    val LANGUAGES: List<String> = %s" % klist(languages))
print("    val TAGLINE: Map<String, String> = %s" % kmap(tagline))
print()
print("    /** Base URL for published static data packs. */")
print('    const val STATIC_PACKS_BASE_URL: String = URL + "/data"')
print()
print("    /** https deep-link prefix validated by every client. */")
print('    const val DEEP_LINK_HTTPS_PREFIX: String = URL')
print()
print("    /** Custom scheme deep-link prefix validated by every client. */")
print('    const val DEEP_LINK_SCHEME_PREFIX: String = URL_SCHEME + "://"')
print()
print("    fun tagline(languageTag: String): String =")
print("        TAGLINE[languageTag] ?: TAGLINE[DEFAULT_LANGUAGE] ?: NAME")
print("}")
PY
}

if [[ "${1:-}" == "--check" ]]; then
  tmp="$(mktemp)"
  trap 'rm -f "${tmp}"' EXIT
  generate > "${tmp}"
  if ! diff -u "${out_file}" "${tmp}"; then
    echo "error: Brand.kt is stale. Run scripts/shared-generate-brand.sh" >&2
    exit 1
  fi
  echo "Brand.kt is up to date with brand.json"
  exit 0
fi

mkdir -p "$(dirname "${out_file}")"
generate > "${out_file}"
echo "wrote ${out_file}"
